### ISSUE TITLE
invalid data type

### ISSUE THREAD

**Issue by wisderfin** [kohiry/blog#17]
https://github.com/kohiry/blog/blob/df103cdb08fe880e2777a2811440e9d0d4544bf4/app/config/settings.py#L17

Use a string instead of a number, because in case of passing an argument an error will occur. you haven't encountered it because you use it only in f-string for now

(personal experience)

**Comment by kohiry** [comment]
I think this is bad practice. I have to be sure that it's not a string but a number. In your case, your program fall down when , for example, postgres connection string getting bad value. In my case, program fall down when start and generate settings.
