### ISSUE TITLE
duplicate ports

### ISSUE THREAD

**Issue by wisderfin** [kohiry/blog#4]
https://github.com/kohiry/blog/blob/3f0b92aa0efe6a9a98d02f5528ab71335283241b/docker-compose.yaml#L31-L32

split the ports into `POSTGRES_PORT_FROM` and `POSTGRES_PORT_TO`

**Comment by kohiry** [comment]
I use the same ports for uvicorn. Therefore, I see no point in specifying another option. In the future, I could set up fallback ports.

**Comment by kohiry** [comment]
Woopsi :^) this is postgres.
